### ISSUE TITLE
Make progress video

### ISSUE THREAD

**Issue by MichaelRuddy** [cse110-fa22-group21/cse110-fa22-group21#57]
We will meet at 5pm Tuesday in person to finish the progress video.  We are meeting at this time because the features we will be presenting will be done Monay night.  We want to be sure to plan ahead and make sure we represent our progress optimally.

**Comment by melvyn9** [comment]
The progress video was completed and uploaded by @nrejai on commit #91665d74d7bed39f60429eeb0b6a593b0da2ea13.
